/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Airport {
  'country' : string,
  'city' : string,
  'code' : string,
}
export interface Booking {
  'status' : BookingStatus,
  'flight' : FlightResult,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'passengers' : Array<PassengerDetails>,
  'bookingRef' : string,
}
export type BookingStatus = { 'cancelled' : null } |
  { 'confirmed' : null };
export type CabinClass = { 'first' : null } |
  { 'economy' : null } |
  { 'business' : null };
export interface CreateBookingInput {
  'flight' : FlightResult,
  'passengers' : Array<PassengerDetails>,
}
export interface CreateFormInput {
  'title' : string,
  'description' : string,
  'fields' : Array<FormField>,
}
export interface FieldAnswer { 'value' : string, 'fieldId' : string }
export interface FieldOption { 'optionLabel' : string, 'value' : string }
export type FieldType = { 'text' : null } |
  { 'textarea' : null } |
  { 'email' : null } |
  { 'number' : null } |
  { 'checkbox' : null } |
  { 'dropdown' : null };
export interface FlightPrice { 'currency' : string, 'amount' : number }
export interface FlightResult {
  'cabinClass' : CabinClass,
  'arrivalTime' : string,
  'flightNumber' : string,
  'departureTime' : string,
  'destinationCode' : string,
  'stops' : bigint,
  'durationMinutes' : bigint,
  'availableSeats' : bigint,
  'airline' : string,
  'price' : FlightPrice,
  'flightId' : string,
  'originCode' : string,
}
export interface FlightSearchParams {
  'destination' : string,
  'cabinClass' : CabinClass,
  'tripType' : TripType,
  'departureDate' : string,
  'origin' : string,
  'passengers' : PassengerCounts,
  'returnDate' : [] | [string],
}
export interface Form {
  'id' : FormId,
  'status' : FormStatus,
  'title' : string,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'description' : string,
  'fields' : Array<FormField>,
  'updatedAt' : Timestamp,
}
export interface FormField {
  'id' : string,
  'order' : bigint,
  'fieldLabel' : string,
  'required' : boolean,
  'placeholder' : string,
  'options' : Array<FieldOption>,
  'fieldType' : FieldType,
}
export type FormId = string;
export interface FormResponse {
  'id' : ResponseId,
  'answers' : Array<FieldAnswer>,
  'submittedAt' : Timestamp,
  'formId' : FormId,
}
export type FormStatus = { 'published' : null } |
  { 'draft' : null };
export interface FormSummary {
  'id' : FormId,
  'status' : FormStatus,
  'title' : string,
  'createdAt' : Timestamp,
  'description' : string,
  'updatedAt' : Timestamp,
  'responseCount' : bigint,
}
export interface PassengerCounts {
  'infants' : bigint,
  'children' : bigint,
  'adults' : bigint,
}
export interface PassengerDetails {
  'email' : string,
  'seatPreference' : SeatPreference,
  'phone' : string,
  'lastName' : string,
  'firstName' : string,
}
export interface PopularRoute {
  'destination' : Airport,
  'origin' : Airport,
  'typicalPrice' : [] | [FlightPrice],
}
export type ResponseId = bigint;
export type SeatPreference = { 'aisle' : null } |
  { 'none' : null } |
  { 'middle' : null } |
  { 'window' : null };
export interface SubmitResponseInput {
  'answers' : Array<FieldAnswer>,
  'formId' : FormId,
}
export type Timestamp = bigint;
export type TripType = { 'roundTrip' : null } |
  { 'oneWay' : null };
export interface UpdateFormInput {
  'title' : string,
  'description' : string,
  'fields' : Array<FormField>,
}
export type UserId = Principal;
export interface _SERVICE {
  'cancelBooking' : ActorMethod<[string], boolean>,
  'createBooking' : ActorMethod<[CreateBookingInput], Booking>,
  'createForm' : ActorMethod<[CreateFormInput], Form>,
  'deleteForm' : ActorMethod<[FormId], boolean>,
  'duplicateForm' : ActorMethod<[FormId], [] | [Form]>,
  'exportResponsesCsv' : ActorMethod<[FormId], string>,
  'getAviationstackApiKey' : ActorMethod<[], [] | [string]>,
  'getBookingByRef' : ActorMethod<[string], [] | [Booking]>,
  'getForm' : ActorMethod<[FormId], [] | [Form]>,
  'getPopularRoutes' : ActorMethod<[], Array<PopularRoute>>,
  'getPublishedForm' : ActorMethod<[FormId], [] | [Form]>,
  'getResponses' : ActorMethod<[FormId], Array<FormResponse>>,
  'getUserBookings' : ActorMethod<[], Array<Booking>>,
  'listForms' : ActorMethod<[], Array<FormSummary>>,
  'publishForm' : ActorMethod<[FormId], [] | [Form]>,
  'searchAirports' : ActorMethod<[string], Array<Airport>>,
  'searchFlights' : ActorMethod<[FlightSearchParams], Array<FlightResult>>,
  'setAviationstackApiKey' : ActorMethod<[string], undefined>,
  'submitResponse' : ActorMethod<[SubmitResponseInput], FormResponse>,
  'unpublishForm' : ActorMethod<[FormId], [] | [Form]>,
  'updateForm' : ActorMethod<[FormId, UpdateFormInput], [] | [Form]>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];