/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const CabinClass = IDL.Variant({
  'first' : IDL.Null,
  'economy' : IDL.Null,
  'business' : IDL.Null,
});
export const FlightPrice = IDL.Record({
  'currency' : IDL.Text,
  'amount' : IDL.Float64,
});
export const FlightResult = IDL.Record({
  'cabinClass' : CabinClass,
  'arrivalTime' : IDL.Text,
  'flightNumber' : IDL.Text,
  'departureTime' : IDL.Text,
  'destinationCode' : IDL.Text,
  'stops' : IDL.Nat,
  'durationMinutes' : IDL.Nat,
  'availableSeats' : IDL.Nat,
  'airline' : IDL.Text,
  'price' : FlightPrice,
  'flightId' : IDL.Text,
  'originCode' : IDL.Text,
});
export const SeatPreference = IDL.Variant({
  'aisle' : IDL.Null,
  'none' : IDL.Null,
  'middle' : IDL.Null,
  'window' : IDL.Null,
});
export const PassengerDetails = IDL.Record({
  'email' : IDL.Text,
  'seatPreference' : SeatPreference,
  'phone' : IDL.Text,
  'lastName' : IDL.Text,
  'firstName' : IDL.Text,
});
export const CreateBookingInput = IDL.Record({
  'flight' : FlightResult,
  'passengers' : IDL.Vec(PassengerDetails),
});
export const BookingStatus = IDL.Variant({
  'cancelled' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const UserId = IDL.Principal;
export const Timestamp = IDL.Int;
export const Booking = IDL.Record({
  'status' : BookingStatus,
  'flight' : FlightResult,
  'userId' : UserId,
  'createdAt' : Timestamp,
  'passengers' : IDL.Vec(PassengerDetails),
  'bookingRef' : IDL.Text,
});
export const FieldOption = IDL.Record({
  'optionLabel' : IDL.Text,
  'value' : IDL.Text,
});
export const FieldType = IDL.Variant({
  'text' : IDL.Null,
  'textarea' : IDL.Null,
  'email' : IDL.Null,
  'number' : IDL.Null,
  'checkbox' : IDL.Null,
  'dropdown' : IDL.Null,
});
export const FormField = IDL.Record({
  'id' : IDL.Text,
  'order' : IDL.Nat,
  'fieldLabel' : IDL.Text,
  'required' : IDL.Bool,
  'placeholder' : IDL.Text,
  'options' : IDL.Vec(FieldOption),
  'fieldType' : FieldType,
});
export const CreateFormInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fields' : IDL.Vec(FormField),
});
export const FormId = IDL.Text;
export const FormStatus = IDL.Variant({
  'published' : IDL.Null,
  'draft' : IDL.Null,
});
export const Form = IDL.Record({
  'id' : FormId,
  'status' : FormStatus,
  'title' : IDL.Text,
  'owner' : UserId,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'fields' : IDL.Vec(FormField),
  'updatedAt' : Timestamp,
});
export const Airport = IDL.Record({
  'country' : IDL.Text,
  'city' : IDL.Text,
  'code' : IDL.Text,
});
export const PopularRoute = IDL.Record({
  'destination' : Airport,
  'origin' : Airport,
  'typicalPrice' : IDL.Opt(FlightPrice),
});
export const ResponseId = IDL.Nat;
export const FieldAnswer = IDL.Record({
  'value' : IDL.Text,
  'fieldId' : IDL.Text,
});
export const FormResponse = IDL.Record({
  'id' : ResponseId,
  'answers' : IDL.Vec(FieldAnswer),
  'submittedAt' : Timestamp,
  'formId' : FormId,
});
export const FormSummary = IDL.Record({
  'id' : FormId,
  'status' : FormStatus,
  'title' : IDL.Text,
  'createdAt' : Timestamp,
  'description' : IDL.Text,
  'updatedAt' : Timestamp,
  'responseCount' : IDL.Nat,
});
export const TripType = IDL.Variant({
  'roundTrip' : IDL.Null,
  'oneWay' : IDL.Null,
});
export const PassengerCounts = IDL.Record({
  'infants' : IDL.Nat,
  'children' : IDL.Nat,
  'adults' : IDL.Nat,
});
export const FlightSearchParams = IDL.Record({
  'destination' : IDL.Text,
  'cabinClass' : CabinClass,
  'tripType' : TripType,
  'departureDate' : IDL.Text,
  'origin' : IDL.Text,
  'passengers' : PassengerCounts,
  'returnDate' : IDL.Opt(IDL.Text),
});
export const SubmitResponseInput = IDL.Record({
  'answers' : IDL.Vec(FieldAnswer),
  'formId' : FormId,
});
export const UpdateFormInput = IDL.Record({
  'title' : IDL.Text,
  'description' : IDL.Text,
  'fields' : IDL.Vec(FormField),
});

export const idlService = IDL.Service({
  'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
  'createBooking' : IDL.Func([CreateBookingInput], [Booking], []),
  'createForm' : IDL.Func([CreateFormInput], [Form], []),
  'deleteForm' : IDL.Func([FormId], [IDL.Bool], []),
  'duplicateForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
  'exportResponsesCsv' : IDL.Func([FormId], [IDL.Text], []),
  'getAviationstackApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
  'getBookingByRef' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
  'getForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
  'getPopularRoutes' : IDL.Func([], [IDL.Vec(PopularRoute)], ['query']),
  'getPublishedForm' : IDL.Func([FormId], [IDL.Opt(Form)], ['query']),
  'getResponses' : IDL.Func([FormId], [IDL.Vec(FormResponse)], []),
  'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
  'listForms' : IDL.Func([], [IDL.Vec(FormSummary)], []),
  'publishForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
  'searchAirports' : IDL.Func([IDL.Text], [IDL.Vec(Airport)], ['query']),
  'searchFlights' : IDL.Func(
      [FlightSearchParams],
      [IDL.Vec(FlightResult)],
      ['query'],
    ),
  'setAviationstackApiKey' : IDL.Func([IDL.Text], [], []),
  'submitResponse' : IDL.Func([SubmitResponseInput], [FormResponse], []),
  'unpublishForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
  'updateForm' : IDL.Func([FormId, UpdateFormInput], [IDL.Opt(Form)], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const CabinClass = IDL.Variant({
    'first' : IDL.Null,
    'economy' : IDL.Null,
    'business' : IDL.Null,
  });
  const FlightPrice = IDL.Record({
    'currency' : IDL.Text,
    'amount' : IDL.Float64,
  });
  const FlightResult = IDL.Record({
    'cabinClass' : CabinClass,
    'arrivalTime' : IDL.Text,
    'flightNumber' : IDL.Text,
    'departureTime' : IDL.Text,
    'destinationCode' : IDL.Text,
    'stops' : IDL.Nat,
    'durationMinutes' : IDL.Nat,
    'availableSeats' : IDL.Nat,
    'airline' : IDL.Text,
    'price' : FlightPrice,
    'flightId' : IDL.Text,
    'originCode' : IDL.Text,
  });
  const SeatPreference = IDL.Variant({
    'aisle' : IDL.Null,
    'none' : IDL.Null,
    'middle' : IDL.Null,
    'window' : IDL.Null,
  });
  const PassengerDetails = IDL.Record({
    'email' : IDL.Text,
    'seatPreference' : SeatPreference,
    'phone' : IDL.Text,
    'lastName' : IDL.Text,
    'firstName' : IDL.Text,
  });
  const CreateBookingInput = IDL.Record({
    'flight' : FlightResult,
    'passengers' : IDL.Vec(PassengerDetails),
  });
  const BookingStatus = IDL.Variant({
    'cancelled' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const UserId = IDL.Principal;
  const Timestamp = IDL.Int;
  const Booking = IDL.Record({
    'status' : BookingStatus,
    'flight' : FlightResult,
    'userId' : UserId,
    'createdAt' : Timestamp,
    'passengers' : IDL.Vec(PassengerDetails),
    'bookingRef' : IDL.Text,
  });
  const FieldOption = IDL.Record({
    'optionLabel' : IDL.Text,
    'value' : IDL.Text,
  });
  const FieldType = IDL.Variant({
    'text' : IDL.Null,
    'textarea' : IDL.Null,
    'email' : IDL.Null,
    'number' : IDL.Null,
    'checkbox' : IDL.Null,
    'dropdown' : IDL.Null,
  });
  const FormField = IDL.Record({
    'id' : IDL.Text,
    'order' : IDL.Nat,
    'fieldLabel' : IDL.Text,
    'required' : IDL.Bool,
    'placeholder' : IDL.Text,
    'options' : IDL.Vec(FieldOption),
    'fieldType' : FieldType,
  });
  const CreateFormInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fields' : IDL.Vec(FormField),
  });
  const FormId = IDL.Text;
  const FormStatus = IDL.Variant({
    'published' : IDL.Null,
    'draft' : IDL.Null,
  });
  const Form = IDL.Record({
    'id' : FormId,
    'status' : FormStatus,
    'title' : IDL.Text,
    'owner' : UserId,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'fields' : IDL.Vec(FormField),
    'updatedAt' : Timestamp,
  });
  const Airport = IDL.Record({
    'country' : IDL.Text,
    'city' : IDL.Text,
    'code' : IDL.Text,
  });
  const PopularRoute = IDL.Record({
    'destination' : Airport,
    'origin' : Airport,
    'typicalPrice' : IDL.Opt(FlightPrice),
  });
  const ResponseId = IDL.Nat;
  const FieldAnswer = IDL.Record({ 'value' : IDL.Text, 'fieldId' : IDL.Text });
  const FormResponse = IDL.Record({
    'id' : ResponseId,
    'answers' : IDL.Vec(FieldAnswer),
    'submittedAt' : Timestamp,
    'formId' : FormId,
  });
  const FormSummary = IDL.Record({
    'id' : FormId,
    'status' : FormStatus,
    'title' : IDL.Text,
    'createdAt' : Timestamp,
    'description' : IDL.Text,
    'updatedAt' : Timestamp,
    'responseCount' : IDL.Nat,
  });
  const TripType = IDL.Variant({ 'roundTrip' : IDL.Null, 'oneWay' : IDL.Null });
  const PassengerCounts = IDL.Record({
    'infants' : IDL.Nat,
    'children' : IDL.Nat,
    'adults' : IDL.Nat,
  });
  const FlightSearchParams = IDL.Record({
    'destination' : IDL.Text,
    'cabinClass' : CabinClass,
    'tripType' : TripType,
    'departureDate' : IDL.Text,
    'origin' : IDL.Text,
    'passengers' : PassengerCounts,
    'returnDate' : IDL.Opt(IDL.Text),
  });
  const SubmitResponseInput = IDL.Record({
    'answers' : IDL.Vec(FieldAnswer),
    'formId' : FormId,
  });
  const UpdateFormInput = IDL.Record({
    'title' : IDL.Text,
    'description' : IDL.Text,
    'fields' : IDL.Vec(FormField),
  });
  
  return IDL.Service({
    'cancelBooking' : IDL.Func([IDL.Text], [IDL.Bool], []),
    'createBooking' : IDL.Func([CreateBookingInput], [Booking], []),
    'createForm' : IDL.Func([CreateFormInput], [Form], []),
    'deleteForm' : IDL.Func([FormId], [IDL.Bool], []),
    'duplicateForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
    'exportResponsesCsv' : IDL.Func([FormId], [IDL.Text], []),
    'getAviationstackApiKey' : IDL.Func([], [IDL.Opt(IDL.Text)], []),
    'getBookingByRef' : IDL.Func([IDL.Text], [IDL.Opt(Booking)], ['query']),
    'getForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
    'getPopularRoutes' : IDL.Func([], [IDL.Vec(PopularRoute)], ['query']),
    'getPublishedForm' : IDL.Func([FormId], [IDL.Opt(Form)], ['query']),
    'getResponses' : IDL.Func([FormId], [IDL.Vec(FormResponse)], []),
    'getUserBookings' : IDL.Func([], [IDL.Vec(Booking)], ['query']),
    'listForms' : IDL.Func([], [IDL.Vec(FormSummary)], []),
    'publishForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
    'searchAirports' : IDL.Func([IDL.Text], [IDL.Vec(Airport)], ['query']),
    'searchFlights' : IDL.Func(
        [FlightSearchParams],
        [IDL.Vec(FlightResult)],
        ['query'],
      ),
    'setAviationstackApiKey' : IDL.Func([IDL.Text], [], []),
    'submitResponse' : IDL.Func([SubmitResponseInput], [FormResponse], []),
    'unpublishForm' : IDL.Func([FormId], [IDL.Opt(Form)], []),
    'updateForm' : IDL.Func([FormId, UpdateFormInput], [IDL.Opt(Form)], []),
  });
};

export const init = ({ IDL }) => { return []; };