/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FlightPrice {
    currency: string;
    amount: number;
}
export type Timestamp = bigint;
export type ResponseId = bigint;
export interface FormField {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    placeholder: string;
    options: Array<FieldOption>;
    fieldType: FieldType;
}
export interface FieldAnswer {
    value: string;
    fieldId: string;
}
export interface CreateBookingInput {
    flight: FlightResult;
    passengers: Array<PassengerDetails>;
}
export interface Form {
    id: FormId;
    status: FormStatus;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    description: string;
    fields: Array<FormField>;
    updatedAt: Timestamp;
}
export interface Booking {
    status: BookingStatus;
    flight: FlightResult;
    userId: UserId;
    createdAt: Timestamp;
    passengers: Array<PassengerDetails>;
    bookingRef: string;
}
export type FormId = string;
export interface UpdateFormInput {
    title: string;
    description: string;
    fields: Array<FormField>;
}
export interface CreateFormInput {
    title: string;
    description: string;
    fields: Array<FormField>;
}
export interface PassengerDetails {
    email: string;
    seatPreference: SeatPreference;
    phone: string;
    lastName: string;
    firstName: string;
}
export interface Airport {
    country: string;
    city: string;
    code: string;
}
export interface FormResponse {
    id: ResponseId;
    answers: Array<FieldAnswer>;
    submittedAt: Timestamp;
    formId: FormId;
}
export interface FieldOption {
    optionLabel: string;
    value: string;
}
export type UserId = Principal;
export interface PassengerCounts {
    infants: bigint;
    children: bigint;
    adults: bigint;
}
export interface FlightSearchParams {
    destination: string;
    cabinClass: CabinClass;
    tripType: TripType;
    departureDate: string;
    origin: string;
    passengers: PassengerCounts;
    returnDate?: string;
}
export interface FormSummary {
    id: FormId;
    status: FormStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    responseCount: bigint;
}
export interface FlightResult {
    cabinClass: CabinClass;
    arrivalTime: string;
    flightNumber: string;
    departureTime: string;
    destinationCode: string;
    stops: bigint;
    durationMinutes: bigint;
    availableSeats: bigint;
    airline: string;
    price: FlightPrice;
    flightId: string;
    originCode: string;
}
export interface SubmitResponseInput {
    answers: Array<FieldAnswer>;
    formId: FormId;
}
export interface PopularRoute {
    destination: Airport;
    origin: Airport;
    typicalPrice?: FlightPrice;
}
export enum BookingStatus {
    cancelled = "cancelled",
    confirmed = "confirmed"
}
export enum CabinClass {
    first = "first",
    economy = "economy",
    business = "business"
}
export enum FieldType {
    text = "text",
    textarea = "textarea",
    email = "email",
    number_ = "number",
    checkbox = "checkbox",
    dropdown = "dropdown"
}
export enum FormStatus {
    published = "published",
    draft = "draft"
}
export enum SeatPreference {
    aisle = "aisle",
    none = "none",
    middle = "middle",
    window_ = "window"
}
export enum TripType {
    roundTrip = "roundTrip",
    oneWay = "oneWay"
}
export interface backendInterface {
    cancelBooking(bookingRef: string): Promise<boolean>;
    createBooking(input: CreateBookingInput): Promise<Booking>;
    createForm(input: CreateFormInput): Promise<Form>;
    deleteForm(formId: FormId): Promise<boolean>;
    duplicateForm(formId: FormId): Promise<Form | null>;
    exportResponsesCsv(formId: FormId): Promise<string>;
    getAviationstackApiKey(): Promise<string | null>;
    getBookingByRef(ref: string): Promise<Booking | null>;
    getForm(formId: FormId): Promise<Form | null>;
    getPopularRoutes(): Promise<Array<PopularRoute>>;
    getPublishedForm(formId: FormId): Promise<Form | null>;
    getResponses(formId: FormId): Promise<Array<FormResponse>>;
    getUserBookings(): Promise<Array<Booking>>;
    listForms(): Promise<Array<FormSummary>>;
    publishForm(formId: FormId): Promise<Form | null>;
    searchAirports(searchTerm: string): Promise<Array<Airport>>;
    searchFlights(params: FlightSearchParams): Promise<Array<FlightResult>>;
    setAviationstackApiKey(key: string): Promise<void>;
    submitResponse(input: SubmitResponseInput): Promise<FormResponse>;
    unpublishForm(formId: FormId): Promise<Form | null>;
    updateForm(formId: FormId, input: UpdateFormInput): Promise<Form | null>;
}
import type { Airport as _Airport, Booking as _Booking, BookingStatus as _BookingStatus, CabinClass as _CabinClass, CreateBookingInput as _CreateBookingInput, CreateFormInput as _CreateFormInput, FieldOption as _FieldOption, FieldType as _FieldType, FlightPrice as _FlightPrice, FlightResult as _FlightResult, FlightSearchParams as _FlightSearchParams, Form as _Form, FormField as _FormField, FormId as _FormId, FormStatus as _FormStatus, FormSummary as _FormSummary, PassengerCounts as _PassengerCounts, PassengerDetails as _PassengerDetails, PopularRoute as _PopularRoute, SeatPreference as _SeatPreference, Timestamp as _Timestamp, TripType as _TripType, UpdateFormInput as _UpdateFormInput, UserId as _UserId } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async cancelBooking(arg0: string): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.cancelBooking(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.cancelBooking(arg0);
            return result;
        }
    }
    async createBooking(arg0: CreateBookingInput): Promise<Booking> {
        if (this.processError) {
            try {
                const result = await this.actor.createBooking(to_candid_CreateBookingInput_n1(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createBooking(to_candid_CreateBookingInput_n1(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Booking_n12(this._uploadFile, this._downloadFile, result);
        }
    }
    async createForm(arg0: CreateFormInput): Promise<Form> {
        if (this.processError) {
            try {
                const result = await this.actor.createForm(to_candid_CreateFormInput_n25(this._uploadFile, this._downloadFile, arg0));
                return from_candid_Form_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createForm(to_candid_CreateFormInput_n25(this._uploadFile, this._downloadFile, arg0));
            return from_candid_Form_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteForm(arg0: FormId): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteForm(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteForm(arg0);
            return result;
        }
    }
    async duplicateForm(arg0: FormId): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.duplicateForm(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.duplicateForm(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async exportResponsesCsv(arg0: FormId): Promise<string> {
        if (this.processError) {
            try {
                const result = await this.actor.exportResponsesCsv(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.exportResponsesCsv(arg0);
            return result;
        }
    }
    async getAviationstackApiKey(): Promise<string | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getAviationstackApiKey();
                return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAviationstackApiKey();
            return from_candid_opt_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getBookingByRef(arg0: string): Promise<Booking | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getBookingByRef(arg0);
                return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getBookingByRef(arg0);
            return from_candid_opt_n43(this._uploadFile, this._downloadFile, result);
        }
    }
    async getForm(arg0: FormId): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getForm(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getForm(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPopularRoutes(): Promise<Array<PopularRoute>> {
        if (this.processError) {
            try {
                const result = await this.actor.getPopularRoutes();
                return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPopularRoutes();
            return from_candid_vec_n44(this._uploadFile, this._downloadFile, result);
        }
    }
    async getPublishedForm(arg0: FormId): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getPublishedForm(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getPublishedForm(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async getResponses(arg0: FormId): Promise<Array<FormResponse>> {
        if (this.processError) {
            try {
                const result = await this.actor.getResponses(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getResponses(arg0);
            return result;
        }
    }
    async getUserBookings(): Promise<Array<Booking>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserBookings();
                return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserBookings();
            return from_candid_vec_n48(this._uploadFile, this._downloadFile, result);
        }
    }
    async listForms(): Promise<Array<FormSummary>> {
        if (this.processError) {
            try {
                const result = await this.actor.listForms();
                return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listForms();
            return from_candid_vec_n49(this._uploadFile, this._downloadFile, result);
        }
    }
    async publishForm(arg0: FormId): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.publishForm(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.publishForm(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async searchAirports(arg0: string): Promise<Array<Airport>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchAirports(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchAirports(arg0);
            return result;
        }
    }
    async searchFlights(arg0: FlightSearchParams): Promise<Array<FlightResult>> {
        if (this.processError) {
            try {
                const result = await this.actor.searchFlights(to_candid_FlightSearchParams_n52(this._uploadFile, this._downloadFile, arg0));
                return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.searchFlights(to_candid_FlightSearchParams_n52(this._uploadFile, this._downloadFile, arg0));
            return from_candid_vec_n56(this._uploadFile, this._downloadFile, result);
        }
    }
    async setAviationstackApiKey(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setAviationstackApiKey(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setAviationstackApiKey(arg0);
            return result;
        }
    }
    async submitResponse(arg0: SubmitResponseInput): Promise<FormResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.submitResponse(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.submitResponse(arg0);
            return result;
        }
    }
    async unpublishForm(arg0: FormId): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.unpublishForm(arg0);
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.unpublishForm(arg0);
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateForm(arg0: FormId, arg1: UpdateFormInput): Promise<Form | null> {
        if (this.processError) {
            try {
                const result = await this.actor.updateForm(arg0, to_candid_UpdateFormInput_n57(this._uploadFile, this._downloadFile, arg1));
                return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateForm(arg0, to_candid_UpdateFormInput_n57(this._uploadFile, this._downloadFile, arg1));
            return from_candid_opt_n41(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_BookingStatus_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _BookingStatus): BookingStatus {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_Booking_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Booking): Booking {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_CabinClass_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _CabinClass): CabinClass {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_FieldType_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FieldType): FieldType {
    return from_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function from_candid_FlightResult_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FlightResult): FlightResult {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_FormField_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormField): FormField {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_FormStatus_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormStatus): FormStatus {
    return from_candid_variant_n35(_uploadFile, _downloadFile, value);
}
function from_candid_FormSummary_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FormSummary): FormSummary {
    return from_candid_record_n51(_uploadFile, _downloadFile, value);
}
function from_candid_Form_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Form): Form {
    return from_candid_record_n33(_uploadFile, _downloadFile, value);
}
function from_candid_PassengerDetails_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PassengerDetails): PassengerDetails {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_PopularRoute_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PopularRoute): PopularRoute {
    return from_candid_record_n46(_uploadFile, _downloadFile, value);
}
function from_candid_SeatPreference_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SeatPreference): SeatPreference {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Form]): Form | null {
    return value.length === 0 ? null : from_candid_Form_n32(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [string]): string | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Booking]): Booking | null {
    return value.length === 0 ? null : from_candid_Booking_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_FlightPrice]): FlightPrice | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _BookingStatus;
    flight: _FlightResult;
    userId: _UserId;
    createdAt: _Timestamp;
    passengers: Array<_PassengerDetails>;
    bookingRef: string;
}): {
    status: BookingStatus;
    flight: FlightResult;
    userId: UserId;
    createdAt: Timestamp;
    passengers: Array<PassengerDetails>;
    bookingRef: string;
} {
    return {
        status: from_candid_BookingStatus_n14(_uploadFile, _downloadFile, value.status),
        flight: from_candid_FlightResult_n16(_uploadFile, _downloadFile, value.flight),
        userId: value.userId,
        createdAt: value.createdAt,
        passengers: from_candid_vec_n20(_uploadFile, _downloadFile, value.passengers),
        bookingRef: value.bookingRef
    };
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cabinClass: _CabinClass;
    arrivalTime: string;
    flightNumber: string;
    departureTime: string;
    destinationCode: string;
    stops: bigint;
    durationMinutes: bigint;
    availableSeats: bigint;
    airline: string;
    price: _FlightPrice;
    flightId: string;
    originCode: string;
}): {
    cabinClass: CabinClass;
    arrivalTime: string;
    flightNumber: string;
    departureTime: string;
    destinationCode: string;
    stops: bigint;
    durationMinutes: bigint;
    availableSeats: bigint;
    airline: string;
    price: FlightPrice;
    flightId: string;
    originCode: string;
} {
    return {
        cabinClass: from_candid_CabinClass_n18(_uploadFile, _downloadFile, value.cabinClass),
        arrivalTime: value.arrivalTime,
        flightNumber: value.flightNumber,
        departureTime: value.departureTime,
        destinationCode: value.destinationCode,
        stops: value.stops,
        durationMinutes: value.durationMinutes,
        availableSeats: value.availableSeats,
        airline: value.airline,
        price: value.price,
        flightId: value.flightId,
        originCode: value.originCode
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    seatPreference: _SeatPreference;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    email: string;
    seatPreference: SeatPreference;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        email: value.email,
        seatPreference: from_candid_SeatPreference_n23(_uploadFile, _downloadFile, value.seatPreference),
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function from_candid_record_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FormId;
    status: _FormStatus;
    title: string;
    owner: _UserId;
    createdAt: _Timestamp;
    description: string;
    fields: Array<_FormField>;
    updatedAt: _Timestamp;
}): {
    id: FormId;
    status: FormStatus;
    title: string;
    owner: UserId;
    createdAt: Timestamp;
    description: string;
    fields: Array<FormField>;
    updatedAt: Timestamp;
} {
    return {
        id: value.id,
        status: from_candid_FormStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        owner: value.owner,
        createdAt: value.createdAt,
        description: value.description,
        fields: from_candid_vec_n36(_uploadFile, _downloadFile, value.fields),
        updatedAt: value.updatedAt
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    placeholder: string;
    options: Array<_FieldOption>;
    fieldType: _FieldType;
}): {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    placeholder: string;
    options: Array<FieldOption>;
    fieldType: FieldType;
} {
    return {
        id: value.id,
        order: value.order,
        fieldLabel: value.fieldLabel,
        required: value.required,
        placeholder: value.placeholder,
        options: value.options,
        fieldType: from_candid_FieldType_n39(_uploadFile, _downloadFile, value.fieldType)
    };
}
function from_candid_record_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: _Airport;
    origin: _Airport;
    typicalPrice: [] | [_FlightPrice];
}): {
    destination: Airport;
    origin: Airport;
    typicalPrice?: FlightPrice;
} {
    return {
        destination: value.destination,
        origin: value.origin,
        typicalPrice: record_opt_to_undefined(from_candid_opt_n47(_uploadFile, _downloadFile, value.typicalPrice))
    };
}
function from_candid_record_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _FormId;
    status: _FormStatus;
    title: string;
    createdAt: _Timestamp;
    description: string;
    updatedAt: _Timestamp;
    responseCount: bigint;
}): {
    id: FormId;
    status: FormStatus;
    title: string;
    createdAt: Timestamp;
    description: string;
    updatedAt: Timestamp;
    responseCount: bigint;
} {
    return {
        id: value.id,
        status: from_candid_FormStatus_n34(_uploadFile, _downloadFile, value.status),
        title: value.title,
        createdAt: value.createdAt,
        description: value.description,
        updatedAt: value.updatedAt,
        responseCount: value.responseCount
    };
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cancelled: null;
} | {
    confirmed: null;
}): BookingStatus {
    return "cancelled" in value ? BookingStatus.cancelled : "confirmed" in value ? BookingStatus.confirmed : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    first: null;
} | {
    economy: null;
} | {
    business: null;
}): CabinClass {
    return "first" in value ? CabinClass.first : "economy" in value ? CabinClass.economy : "business" in value ? CabinClass.business : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    aisle: null;
} | {
    none: null;
} | {
    middle: null;
} | {
    window: null;
}): SeatPreference {
    return "aisle" in value ? SeatPreference.aisle : "none" in value ? SeatPreference.none : "middle" in value ? SeatPreference.middle : "window" in value ? SeatPreference.window : value;
}
function from_candid_variant_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    published: null;
} | {
    draft: null;
}): FormStatus {
    return "published" in value ? FormStatus.published : "draft" in value ? FormStatus.draft : value;
}
function from_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    text: null;
} | {
    textarea: null;
} | {
    email: null;
} | {
    number: null;
} | {
    checkbox: null;
} | {
    dropdown: null;
}): FieldType {
    return "text" in value ? FieldType.text : "textarea" in value ? FieldType.textarea : "email" in value ? FieldType.email : "number" in value ? FieldType.number : "checkbox" in value ? FieldType.checkbox : "dropdown" in value ? FieldType.dropdown : value;
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PassengerDetails>): Array<PassengerDetails> {
    return value.map((x)=>from_candid_PassengerDetails_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormField>): Array<FormField> {
    return value.map((x)=>from_candid_FormField_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_PopularRoute>): Array<PopularRoute> {
    return value.map((x)=>from_candid_PopularRoute_n45(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Booking>): Array<Booking> {
    return value.map((x)=>from_candid_Booking_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FormSummary>): Array<FormSummary> {
    return value.map((x)=>from_candid_FormSummary_n50(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_FlightResult>): Array<FlightResult> {
    return value.map((x)=>from_candid_FlightResult_n16(_uploadFile, _downloadFile, x));
}
function to_candid_CabinClass_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CabinClass): _CabinClass {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_CreateBookingInput_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateBookingInput): _CreateBookingInput {
    return to_candid_record_n2(_uploadFile, _downloadFile, value);
}
function to_candid_CreateFormInput_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CreateFormInput): _CreateFormInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_FieldType_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldType): _FieldType {
    return to_candid_variant_n31(_uploadFile, _downloadFile, value);
}
function to_candid_FlightResult_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightResult): _FlightResult {
    return to_candid_record_n4(_uploadFile, _downloadFile, value);
}
function to_candid_FlightSearchParams_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FlightSearchParams): _FlightSearchParams {
    return to_candid_record_n53(_uploadFile, _downloadFile, value);
}
function to_candid_FormField_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FormField): _FormField {
    return to_candid_record_n29(_uploadFile, _downloadFile, value);
}
function to_candid_PassengerDetails_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PassengerDetails): _PassengerDetails {
    return to_candid_record_n9(_uploadFile, _downloadFile, value);
}
function to_candid_SeatPreference_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeatPreference): _SeatPreference {
    return to_candid_variant_n11(_uploadFile, _downloadFile, value);
}
function to_candid_TripType_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripType): _TripType {
    return to_candid_variant_n55(_uploadFile, _downloadFile, value);
}
function to_candid_UpdateFormInput_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UpdateFormInput): _UpdateFormInput {
    return to_candid_record_n26(_uploadFile, _downloadFile, value);
}
function to_candid_record_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flight: FlightResult;
    passengers: Array<PassengerDetails>;
}): {
    flight: _FlightResult;
    passengers: Array<_PassengerDetails>;
} {
    return {
        flight: to_candid_FlightResult_n3(_uploadFile, _downloadFile, value.flight),
        passengers: to_candid_vec_n7(_uploadFile, _downloadFile, value.passengers)
    };
}
function to_candid_record_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    title: string;
    description: string;
    fields: Array<FormField>;
}): {
    title: string;
    description: string;
    fields: Array<_FormField>;
} {
    return {
        title: value.title,
        description: value.description,
        fields: to_candid_vec_n27(_uploadFile, _downloadFile, value.fields)
    };
}
function to_candid_record_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    placeholder: string;
    options: Array<FieldOption>;
    fieldType: FieldType;
}): {
    id: string;
    order: bigint;
    fieldLabel: string;
    required: boolean;
    placeholder: string;
    options: Array<_FieldOption>;
    fieldType: _FieldType;
} {
    return {
        id: value.id,
        order: value.order,
        fieldLabel: value.fieldLabel,
        required: value.required,
        placeholder: value.placeholder,
        options: value.options,
        fieldType: to_candid_FieldType_n30(_uploadFile, _downloadFile, value.fieldType)
    };
}
function to_candid_record_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    cabinClass: CabinClass;
    arrivalTime: string;
    flightNumber: string;
    departureTime: string;
    destinationCode: string;
    stops: bigint;
    durationMinutes: bigint;
    availableSeats: bigint;
    airline: string;
    price: FlightPrice;
    flightId: string;
    originCode: string;
}): {
    cabinClass: _CabinClass;
    arrivalTime: string;
    flightNumber: string;
    departureTime: string;
    destinationCode: string;
    stops: bigint;
    durationMinutes: bigint;
    availableSeats: bigint;
    airline: string;
    price: _FlightPrice;
    flightId: string;
    originCode: string;
} {
    return {
        cabinClass: to_candid_CabinClass_n5(_uploadFile, _downloadFile, value.cabinClass),
        arrivalTime: value.arrivalTime,
        flightNumber: value.flightNumber,
        departureTime: value.departureTime,
        destinationCode: value.destinationCode,
        stops: value.stops,
        durationMinutes: value.durationMinutes,
        availableSeats: value.availableSeats,
        airline: value.airline,
        price: value.price,
        flightId: value.flightId,
        originCode: value.originCode
    };
}
function to_candid_record_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    destination: string;
    cabinClass: CabinClass;
    tripType: TripType;
    departureDate: string;
    origin: string;
    passengers: PassengerCounts;
    returnDate?: string;
}): {
    destination: string;
    cabinClass: _CabinClass;
    tripType: _TripType;
    departureDate: string;
    origin: string;
    passengers: _PassengerCounts;
    returnDate: [] | [string];
} {
    return {
        destination: value.destination,
        cabinClass: to_candid_CabinClass_n5(_uploadFile, _downloadFile, value.cabinClass),
        tripType: to_candid_TripType_n54(_uploadFile, _downloadFile, value.tripType),
        departureDate: value.departureDate,
        origin: value.origin,
        passengers: value.passengers,
        returnDate: value.returnDate ? candid_some(value.returnDate) : candid_none()
    };
}
function to_candid_record_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    email: string;
    seatPreference: SeatPreference;
    phone: string;
    lastName: string;
    firstName: string;
}): {
    email: string;
    seatPreference: _SeatPreference;
    phone: string;
    lastName: string;
    firstName: string;
} {
    return {
        email: value.email,
        seatPreference: to_candid_SeatPreference_n10(_uploadFile, _downloadFile, value.seatPreference),
        phone: value.phone,
        lastName: value.lastName,
        firstName: value.firstName
    };
}
function to_candid_variant_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: SeatPreference): {
    aisle: null;
} | {
    none: null;
} | {
    middle: null;
} | {
    window: null;
} {
    return value == SeatPreference.aisle ? {
        aisle: null
    } : value == SeatPreference.none ? {
        none: null
    } : value == SeatPreference.middle ? {
        middle: null
    } : value == SeatPreference.window ? {
        window_: null
    } : value;
}
function to_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: FieldType): {
    text: null;
} | {
    textarea: null;
} | {
    email: null;
} | {
    number: null;
} | {
    checkbox: null;
} | {
    dropdown: null;
} {
    return value == FieldType.text ? {
        text: null
    } : value == FieldType.textarea ? {
        textarea: null
    } : value == FieldType.email ? {
        email: null
    } : value == FieldType.number ? {
        number_: null
    } : value == FieldType.checkbox ? {
        checkbox: null
    } : value == FieldType.dropdown ? {
        dropdown: null
    } : value;
}
function to_candid_variant_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: TripType): {
    roundTrip: null;
} | {
    oneWay: null;
} {
    return value == TripType.roundTrip ? {
        roundTrip: null
    } : value == TripType.oneWay ? {
        oneWay: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: CabinClass): {
    first: null;
} | {
    economy: null;
} | {
    business: null;
} {
    return value == CabinClass.first ? {
        first: null
    } : value == CabinClass.economy ? {
        economy: null
    } : value == CabinClass.business ? {
        business: null
    } : value;
}
function to_candid_vec_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<FormField>): Array<_FormField> {
    return value.map((x)=>to_candid_FormField_n28(_uploadFile, _downloadFile, x));
}
function to_candid_vec_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<PassengerDetails>): Array<_PassengerDetails> {
    return value.map((x)=>to_candid_PassengerDetails_n8(_uploadFile, _downloadFile, x));
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
